# Generated by Django 2.2.4 on 2020-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(blank=True, max_length=100)),
                ('portfolio_name', models.CharField(blank=True, default='', max_length=100)),
                ('portfolio_index', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('cloned_from', models.CharField(blank=True, default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
