# Generated by Django 2.2.4 on 2020-05-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stox9GameService', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
