# Generated by Django 2.2.4 on 2020-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stox9GameService', '0003_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfolio',
            old_name='user_id',
            new_name='userId',
        ),
    ]
