# Generated by Django 2.2.4 on 2020-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stox9GameService', '0004_auto_20200527_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='contestPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.CharField(blank=True, default='', max_length=100)),
                ('portfolioId', models.CharField(blank=True, max_length=100)),
                ('planId', models.CharField(blank=True, default='', max_length=100)),
                ('poolId', models.CharField(blank=True, default='', max_length=100)),
                ('userId', models.CharField(blank=True, default='', max_length=100)),
                ('userUniqueId', models.CharField(blank=True, default='', max_length=100)),
                ('totalPoints', models.IntegerField(blank=True, null=True)),
                ('wonTurtles', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('refTxnId', models.CharField(blank=True, default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planId', models.CharField(blank=True, default='', max_length=100)),
                ('isConfirmWinnings', models.BooleanField(blank=True, default=False)),
                ('isDefault', models.BooleanField(blank=True, default=False)),
                ('isRepetitive', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('maxTeams', models.IntegerField(blank=True, null=True)),
                ('canApplyBonus', models.BooleanField(blank=True, default=False)),
                ('canApplyPass', models.BooleanField(blank=True, default=False)),
                ('entryFee', models.IntegerField(blank=True, null=True)),
                ('totalWinners', models.IntegerField(blank=True, null=True)),
                ('rake', models.IntegerField(blank=True, null=True)),
                ('prizePool', models.IntegerField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestId', models.CharField(blank=True, default='', max_length=100)),
                ('poolId', models.CharField(blank=True, max_length=100)),
                ('planId', models.CharField(blank=True, default='', max_length=100)),
                ('isCancelled', models.BooleanField(blank=True, default=False)),
                ('isFilled', models.BooleanField(blank=True, default=False)),
                ('paymentStatus', models.BooleanField(blank=True, default=False)),
                ('spotsLeft', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='portfolio_id',
            new_name='portfolioId',
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='portfolio_index',
            new_name='portfolioIndex',
        ),
        migrations.RenameField(
            model_name='userportfolio',
            old_name='portfolio_name',
            new_name='portfolioName',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='userUniqueId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
